server:
  port: 8080
spring:
  application:
    name: template-service
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=yes&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234
    maximum-pool-size: 2    #커넥션 사이즈
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 1000
        query:
          plan_cache_max_size: 500
          plan_parameter_metadata_max_size: 32
  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false #Lazy 로딩 시, 오류 방지
#  sql: # 초기 데이터 input
#    init:
#      data-locations: classpath:data.sql
#      mode: always

logging:
  level:
    root: warn
    org.hibernate.SQL: warn
    org.hibernate.type: warn
    org.hibernate:
      type:
        descriptor.sql: warn


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: prometheus,health,info

eureka:
  client:
#    register-with-eureka: true
#    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: false

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /doc
    tryItOutEnabled: true
    tagsSorter: alpha
    filter: true